# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-16 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20160712_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cep',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='CEP'),
        ),
    ]
