# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-23 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20160716_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Conta', 'verbose_name_plural': 'Contas'},
        ),
        migrations.AlterField(
            model_name='accountdeletion',
            name='date_expunged',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do expurgo'),
        ),
        migrations.AlterField(
            model_name='accountdeletion',
            name='date_requested',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Requisi\xe7\xe3o'),
        ),
    ]
