# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-24 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20160723_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='account',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='account',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='account',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='account',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='account',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='account',
            name='logradouro',
        ),
        migrations.RemoveField(
            model_name='account',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='account',
            name='telefone',
        ),
    ]
