# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 23:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Cliente', max_length=220, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, max_length=200, null=True, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fone')),
                ('cep', models.IntegerField(blank=True, null=True, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, help_text='Nome da rua, avenida, etc.', max_length=200, null=True, verbose_name='Logradouro')),
                ('complemento', models.CharField(blank=True, max_length=200, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_cliente', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Plano', max_length=220, verbose_name='Plano')),
                ('telefone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fone')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerencial.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(verbose_name='Pago')),
                ('assinatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gerencial.Assinatura')),
            ],
        ),
        migrations.CreateModel(
            name='Indicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Plano', max_length=220, verbose_name='Plano')),
                ('telefone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fone')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerencial.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Plano', max_length=220, verbose_name='Plano')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Plano', max_length=220, verbose_name='Plano')),
                ('fonte', models.IntegerField(choices=[(1, 'Newsletter'), (2, 'Experimente')], default=1, verbose_name='Fonte do Prospect')),
                ('categoria', models.IntegerField(choices=[(1, 'Compartilhado'), (2, 'Camera IP')], default=1, verbose_name='Categoria do Prospect')),
                ('interesse', models.IntegerField(choices=[(1, 'Compartilhado'), (2, 'Camera IP')], default=1, verbose_name='Interesse do Prospect')),
            ],
        ),
        migrations.AddField(
            model_name='assinatura',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerencial.Cliente'),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerencial.Plano'),
        ),
    ]
