# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerencial', '0002_auto_20160711_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_cliente', to='account.Account', verbose_name='usuario'),
        ),
    ]
