# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-16 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencial', '0004_auto_20160712_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='aceite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='contrato',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fatura',
            name='ano',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fatura',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='nome',
            field=models.CharField(help_text='Nome do Dependente', max_length=220, verbose_name='Dependente'),
        ),
        migrations.AlterField(
            model_name='indicacao',
            name='nome',
            field=models.CharField(help_text='Nome do Indicado', max_length=220, verbose_name='Indicado'),
        ),
    ]
