# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-17 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencial', '0005_auto_20160716_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='termo_utilizacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='contrato',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
