# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-19 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencial', '0006_auto_20160717_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='bairro',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='cidade',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='mensagem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='telefone',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='fonte',
            field=models.IntegerField(choices=[(1, 'Newsletter'), (2, 'Experimente'), (2, 'Contato')], default=1, verbose_name='Fonte do Prospect'),
        ),
    ]
