# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-23 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20160723_2248'),
        ('gerencial', '0007_auto_20160719_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome do Cliente', max_length=220, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, max_length=200, null=True, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fone')),
                ('cep', models.IntegerField(blank=True, null=True, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, help_text='Nome da rua, avenida, etc.', max_length=200, null=True, verbose_name='Logradouro')),
                ('complemento', models.CharField(blank=True, max_length=200, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_cliente', to='account.Account', verbose_name='usuario')),
            ],
        ),
        migrations.AlterModelOptions(
            name='indicacao',
            options={'verbose_name': 'Indica\xe7\xe3o', 'verbose_name_plural': 'Indica\xe7\xf5es'},
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='termo_utilizacao',
            field=models.TextField(blank=True, default='Texto do termo de utiliza\xe7\xe3o padr\xe3o, a ser definido.', null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'Compartilhado'), (2, 'Camera IP')], default=1, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='fonte',
            field=models.IntegerField(choices=[(1, 'Newsletter'), (2, 'Experimente'), (2, 'Contato')], default=1, verbose_name='Fonte'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='interesse',
            field=models.IntegerField(choices=[(1, '25%'), (2, '50%'), (2, '75%'), (2, '100%')], default=1, verbose_name='Interesse'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='nome',
            field=models.CharField(help_text='Nome', max_length=220, verbose_name='Nome'),
        ),
    ]
